"""
Vihaan Nama & Lennox Anderson
AIPI 510 Sourcing for Data
Disclaimer: Parts of this code was generated by Perplexity and Claude
"""

import json
import boto3

import io
import base64


def read_from_s3(event, context):
    """
    AWS Lambda function that reads a CSV file from S3 and returns it

    Parameters:
    event (dict): Must contain:
        - bucket_name: S3 bucket name
        - file_key: Path to CSV file in the bucket
    context (LambdaContext): AWS Lambda Context object

    Returns:
    dict: Lambda response containing:
        - statusCode: HTTP status code
        - body: CSV data as a base64 encoded string
    """
    try:
        # Get bucket and file information from the event
        bucket_name = "ta10-data"
        file_key = "youtube_channel_real_performance_analytics.csv"

        # Initialize S3 client
        s3_client = boto3.client('s3')

        # Read the CSV file from S3
        response = s3_client.get_object(Bucket=bucket_name, Key=file_key)
        csv_content = response['Body'].read().decode('utf-8')

        return {
            'statusCode': 200,
            'body': csv_content,
            'headers': {
                'Content-Type': 'text/csv',
                'Content-Disposition': f'attachment; filename="{file_key}"'
            }
        }

    except Exception as e:
        return {
            'statusCode': 500,
            'body': json.dumps({
                'error': str(e)
            })
        }