"""
Vihaan Nama & Lennox Anderson
AIPI 510 Sourcing for Data
Disclaimer: Parts of this code was generated by Perplexity and Claude
"""

import json
import boto3
from datetime import datetime


def write_to_s3(event, context):
    """
    AWS Lambda function that writes CSV data from the input to an S3 file

    Parameters:
    event (dict): Must contain:
        - bucket_name: S3 bucket name
        - file_name: Name for the CSV file
        - body: CSV data as a string

    Returns:
    dict: Lambda response containing:
        - statusCode: HTTP status code
        - body: Success/error message with file details
    """
    try:
        # Extract parameters from the event
        bucket_name = event.get('bucket_name')
        file_name = event.get('file_name')
        csv_data = event.get('body')

        # Validate input
        if not bucket_name:
            return {
                'statusCode': 400,
                'body': json.dumps({
                    'error': 'Missing required parameter: bucket_name'
                })
            }

        if not file_name:
            return {
                'statusCode': 400,
                'body': json.dumps({
                    'error': 'Missing required parameter: file_name'
                })
            }

        if not csv_data:
            return {
                'statusCode': 400,
                'body': json.dumps({
                    'error': 'No CSV data provided in the body'
                })
            }

        # Ensure .csv extension
        if not file_name.endswith('.csv'):
            file_name += '.csv'

        # Initialize S3 client
        s3_client = boto3.client('s3')

        # Upload CSV to S3
        s3_client.put_object(
            Bucket=bucket_name,
            Key=file_name,
            Body=csv_data.encode('utf-8'),
            ContentType='text/csv'
        )

        # Count rows in CSV data
        rows_count = len(csv_data.strip().split('\n')) - 1  # Subtract 1 for header

        return {
            'statusCode': 200,
            'body': json.dumps({
                'message': 'File successfully written to S3',
                'bucket': bucket_name,
                'file_name': file_name,
                'rows_written': rows_count
            })
        }

    except Exception as e:
        # Error handling
        return {
            'statusCode': 500,
            'body': json.dumps({
                'error': f'Error processing request: {str(e)}',
                'details': str(e)
            })
        }