"""
Vihaan Nama & Lennox Anderson
AIPI 510 Sourcing for Data
Disclaimer: Parts of this code was generated by Perplexity and Claude
"""

import csv
import io


def lambda_handler(event, context):
    # Get the CSV input from the event
    csv_input = event['body']

    # Create a StringIO object to work with the CSV data
    csv_file = io.StringIO(csv_input)

    # Read the CSV data
    csv_reader = csv.reader(csv_file)

    # Get the header (first line)
    header = next(csv_reader)

    # Read the first data row
    first_data_row = next(csv_reader)

    # Read the rest of the lines
    rows = list(csv_reader)

    # Append the first data row to the end
    rows.append(first_data_row)

    # Create a new StringIO object for the output
    output = io.StringIO()
    csv_writer = csv.writer(output)

    # Write the header and all rows to the output
    csv_writer.writerow(header)
    csv_writer.writerows(rows)

    # Get the final CSV as a string
    result = output.getvalue()

    return {
        'bucket_name': "ta10-data",
        'file_name': "example.csv",
        'statusCode': 200,
        'body': result
    }