import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

# Page navigation reference: https://discuss.streamlit.io/t/how-to-clear-screen-make-blank-again/30971/2
if 'page' not in st.session_state:
    st.session_state.page = 0

def prevpage(): st.session_state.page -= 1

def nextpage(): st.session_state.page += 1

def escape(): st.session_state.page = 0

def homepage():
    st.write('''
            # The Two-Way ANOVA Test
            ## Welcome to the Post-Apocalyptic ANOVA Bunker Simulator!
            **Greetings, brave survivor!** Don't worry, you're not actually trapped in a bunker surrounded by strange monsters. 
            This is just a fun and slightly unsettling way to explore the fascinating world of Two-Way ANOVA testing.

            Disclaimer: No actual apocalypses were triggered in the making of this application. The monsters outside are purely fictional and are not planning to eat your brain... probably.
            
            Here's what you need to know:

            * You're safe behind your computer screen.
            * The other bunkers can't actually hear your screams.
            * The strange noises you hear are just your neighbor's cat... we hope.

            So sit back, relax, and prepare to dive into the thrilling world of statistical analysis – post-apocalyptic style! 
            Remember, in this simulation, the only thing truly terrifying is a p-value greater than 0.05.
            Now, let's explore how different factors affect survival rates in our imaginary bunker network. Who knows? 
            The skills you learn here might come in handy during the real apocalypse. (Just kidding... or are we?)
            ''')

    left, middle, right = st.columns(3)

    right.button('Start Simulation', type='primary', on_click=nextpage)

    st.divider()

    st.write('''
             *The above text and images in the simulation were generated by Perplexity AI and Google Gemini respectively. The final two images were found from Google Images.*
             ''')

def staged_scene(scene, action_text=None, on_click=None):
    st.button('Esc', type='secondary', on_click=escape)

    scene()

    left, _, right = st.columns(3)
    if st.session_state.page > 1:
        left.button('Back', type='secondary', on_click=prevpage)
    right.button('Next' if action_text == None else action_text, type='primary', on_click=nextpage if on_click == None else on_click)

    st.progress(st.session_state.page / 19)

def scene1():
    st.write('''
             You find yourself in a bunker. The world as you know it has come to an end.
             ''')
    
def scene2():
    st.write('''
             You made it to safety as soon as you heard the reports on the news. You were one of the lucky ones.
             ''')
    
def scene3():
    st.write('''
             A frightening sound emanates from the heavy steel bunker door and reverberates.
             ''')
    
def scene4():
    st.write('''
             You hear a crackle over Discord.
             ''')
    
def scene5():
    st.write('''
             "-one ther-" *nothing* "-ello?! Is anyone there?!"

             The audio comes into focus and you hear a man sobbing on the other end.
             ''')
    
def scene6():
    st.write('''
             The sobbing man: "Oh thank God!"

             Another voice, also sobbing: "Hello?"

             Several other voices tune in, one by one.

             One of them: "What are we going to do?! We can't stay here forever! I'm getting out of here!"
             ''')
    
def scene7():
    st.write('''
             You hear a bunker door creak open, followed by a blood-curdling scream.
             ''')
    
def scene8():
    st.write('''
             You explain to the Discord channel that before you rushed to the bunker, you heard on the news that
             officials speculated that the monsters outside might be zombies, werewolves, or vampires.

             You hear a deafening silence from the channel, as their new reality sinks in.
             ''')

def scene9():
    st.write('''
             "Maybe there's some material or substance in our bunkers that wards off the monsters outside!
             If we can figure out what it is, then whoever has it can leave the bunker and come rescue the others!
             We can rebuild!"

             The channel is silent for a while.

             Someone: "How do we figure out what works?"

             You: "We'll do a **TWO-WAY ANOVA TEST**."

             Another voice: "A two way a-what-a what?"
             ''')
    
def scene10():
    st.write('''
             **The Two-Way ANOVA Test!** ANOVA stands for Analysis of Variance.

             Using the Two-Way ANOVA Test, we can test two different **factors** and their **levels** to see whether they have an effect
             on a continuous outcome variable, and whether they interact with each other. 
             The **factors** are independent categorical variables, where the *levels* are the types within each category.
             The outcome variable is our dependent variable.

             In our case, we can measure the noise coming from outside, and we can report back over this channel with data over the next three hours. 
             And we can report it with

             1. what noteworthy substance is in your bunker. For example, I have some silver here. That should work against werewolves.
             2. whether your bunker has any religious iconography. Vampires hate that.

             Those are our two factors.

             We just need a few things to be true to perform our test.

             1. We need at least 3 groups to record data independently. We should be good there, because we have several bunkers reporting data.
             2. We need our audio data to be normal distributions.
             3. We need the variance of our audio data to be homegenous. We can check this using Bartlett's Test.
             
             Is everyone ready?

             **You're met with an enthusiastic cheer.**
             ''')
    
def scene11():
    st.write('''
             You: "We now have all the data we need. I'll start on the analysis, folks! Please sit back and relax."
             ''')
    
def scene12():
    st.write('''
             PLACEHOLDER FOR NORMALITY TEST
             ''')
    
def scene13():
    st.write('''
             PLACEHOLDER FOR HOMOGENEITY TEST
             ''')

def scene14():
    st.write('''
             PLACEHOLDER FOR GRAND MEAN
             ''')
    
def scene15():
    st.write('''
             PLACEHOLDER FOR SUM OF SQUARES
             ''')
    
def scene16():
    st.write('''
             PLACEHOLDER FOR DEGREES OF FREEDOM
             ''')
    
def scene17():
    st.write('''
             PLACEHOLDER FOR F-STATISTICS
             ''')
    
def scene18():
    st.write('''
             PLACEHOLDER FOR P-VALUE
             ''')
    
def scene19():
    st.write('''
             You: "Now we know there's a chance at warding off these monsters! Whatever they happen to be!"

             Everyone cheers over the channel.

             You: "Now I just need to figure out what specifically worked using a post-hoc test."

             Everyone:

             ![](https://i.redd.it/spongebob-you-what-meme-v0-54he65l7d02b1.png?width=432&format=png&auto=webp&s=e4694bcd8f6051ee80b6e6319a5aa203b55b4532)

             ![](https://preview.redd.it/ss3dlqgtfgq71.jpg?width=640&crop=smart&auto=webp&s=85756c17519cffd04d7e807144ad6abcbd3ddb8a)
             ''')
    
if st.session_state.page == 0:
    homepage()
elif st.session_state.page == 1:
    staged_scene(scene1)
elif st.session_state.page == 2:
    staged_scene(scene2)
elif st.session_state.page == 3:
    staged_scene(scene3, action_text="What was that?!")
elif st.session_state.page == 4:
    staged_scene(scene4, action_text="Tune the radio")
elif st.session_state.page == 5:
    staged_scene(scene5, action_text="Hello!! I'm here!")
elif st.session_state.page == 6:
    staged_scene(scene6, action_text="No, don't do it!!")
elif st.session_state.page == 7:
    staged_scene(scene7, action_text="Next")
elif st.session_state.page == 8:
    staged_scene(scene8, action_text="I have an idea!")
elif st.session_state.page == 9:
    staged_scene(scene9, action_text="Explain")
elif st.session_state.page == 10:
    staged_scene(scene10, action_text="3 hours later...")
elif st.session_state.page == 11:
    staged_scene(scene11, action_text="Check normality")
elif st.session_state.page == 12:
    staged_scene(scene12, action_text="Check homogeneity of variance")
elif st.session_state.page == 13:
    staged_scene(scene13, action_text="Calculate grand mean")
elif st.session_state.page == 14:
    staged_scene(scene14, action_text="Compute Sums of Squares")
elif st.session_state.page == 15:
    staged_scene(scene15, action_text="Compute degrees of freedom (df)")
elif st.session_state.page == 16:
    staged_scene(scene16, action_text="Calculate Mean Squares (MS)")
elif st.session_state.page == 17:
    staged_scene(scene17, action_text="Compute F-statistics")
elif st.session_state.page == 18:
    staged_scene(scene18, action_text="Determine p-value")
elif st.session_state.page == 19:
    staged_scene(scene19, action_text="END", on_click=escape)
